import React, { useState, useMemo } from "react";
import { useData } from "../context/DataContext";
import { useApp } from "../context/AppContext";
import {
    FileText,
    Download,
    Mail,
    Calendar as CalendarIcon,
    CheckCircle2,
    Filter,
    ArrowRight
} from "lucide-react";
import { formatCurrency } from "../utils/format";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function Reports() {
    const { expenses, debtors, payments } = useData();
    const { currency: preferredCurrency } = useApp();

    const [startDate, setStartDate] = useState(
        new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().split("T")[0]
    );
    const [endDate, setEndDate] = useState(new Date().toISOString().split("T")[0]);

    const [includeExpenses, setIncludeExpenses] = useState(true);
    const [includeDebtors, setIncludeDebtors] = useState(true);
    const [includePaidDebtors, setIncludePaidDebtors] = useState(false);

    const [step, setStep] = useState(1); // 1: Setup, 2: Preview

    const reportData = useMemo(() => {
        const start = new Date(startDate);
        const end = new Date(endDate);
        end.setHours(23, 59, 59, 999);

        const filteredExpenses = expenses.filter(e => {
            const d = new Date(e.date || e.createdAt?.toDate?.() || "");
            return d >= start && d <= end;
        });

        const filteredDebtors = debtors.filter(d => {
            const date = new Date(d.createdAt?.toDate?.() || "");
            if (d.status === "paid" && !includePaidDebtors) return false;
            return date >= start && date <= end;
        });

        // Find payments in this period
        const filteredPayments = payments.filter(p => {
            const d = new Date(p.date || p.createdAt?.toDate?.() || "");
            return d >= start && d <= end;
        });

        return {
            expenses: filteredExpenses,
            debtors: filteredDebtors,
            payments: filteredPayments,
            totalExpense: filteredExpenses.reduce((acc, curr) => acc + curr.amount, 0),
            totalDebt: filteredDebtors.reduce((acc, curr) => acc + (curr.amount - (curr.paidAmount || 0)), 0),
        };
    }, [startDate, endDate, expenses, debtors, payments, includePaidDebtors]);

    const generateReportText = () => {
        let text = `SPENDORA FINANCIAL REPORT\n`;
        text += `Period: ${startDate} to ${endDate}\n`;
        text += `-----------------------------------\n\n`;

        if (includeExpenses) {
            text += `EXPENSES SUMMARY\n`;
            text += `Total Expenses: ${formatCurrency(reportData.totalExpense, preferredCurrency)}\n`;
            reportData.expenses.forEach(e => {
                text += `- ${e.date}: ${e.subject || e.description} (${formatCurrency(e.amount, preferredCurrency)})\n`;
            });
            text += `\n`;
        }

        if (includeDebtors) {
            text += `DEBTORS SUMMARY\n`;
            text += `Current Outstanding: ${formatCurrency(reportData.totalDebt, preferredCurrency)}\n`;
            reportData.debtors.forEach(d => {
                const remaining = d.amount - (d.paidAmount || 0);
                text += `- ${d.debtorName}: Total ${formatCurrency(d.amount, preferredCurrency)}, Paid ${formatCurrency(d.paidAmount || 0, preferredCurrency)}, Due ${formatCurrency(remaining, preferredCurrency)}, Contact ${d.email || d.phoneNumber || "N/A"}\n`;
            });
            text += `\n`;
        }

        if (reportData.payments.length > 0) {
            text += `RECENT PAYMENTS RECEIVED\n`;
            reportData.payments.forEach(p => {
                text += `- ${p.date}: ${p.debtorName} paid ${formatCurrency(p.amount, preferredCurrency)} via ${p.method || "Manual Entry"}\n`;
            });
            text += `\n`;
        }

        text += `\nGenerated by Spendora`;
        return text;
    };

    const handleSendEmail = () => {
        const subject = `Spendora Financial Report (${startDate} to ${endDate})`;
        const body = encodeURIComponent(generateReportText());
        window.location.href = `mailto:?subject=${subject}&body=${body}`;
    };

    const handleDownloadPDF = () => {
        const doc = new jsPDF();
        const accentColor: [number, number, number] = [0, 188, 212];
        const darkColor: [number, number, number] = [30, 30, 35];
        const mutedColor: [number, number, number] = [120, 120, 130];
        const pageWidth = doc.internal.pageSize.getWidth();

        // --- Header ---
        doc.setFillColor(...darkColor);
        doc.rect(0, 0, pageWidth, 28, "F");
        doc.setFont("helvetica", "bold");
        doc.setFontSize(22);
        doc.setTextColor(...accentColor);
        doc.text("SPEND", 14, 18);
        const spendWidth = doc.getTextWidth("SPEND");
        doc.setTextColor(255, 255, 255);
        doc.text("ORA", 14 + spendWidth, 18);
        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(180, 180, 190);
        doc.text("Financial Report", pageWidth - 14, 18, { align: "right" });

        // --- Period ---
        doc.setFontSize(10);
        doc.setTextColor(...mutedColor);
        doc.setFont("helvetica", "normal");
        doc.text(`Report Period: ${startDate}  â†’  ${endDate}`, 14, 36);

        // --- Summary Boxes ---
        doc.setFillColor(240, 252, 254);
        doc.roundedRect(14, 42, 82, 20, 4, 4, "F");
        doc.setFontSize(8);
        doc.setTextColor(...mutedColor);
        doc.text("TOTAL EXPENSES", 18, 49);
        doc.setFontSize(13);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(...accentColor);
        doc.text(formatCurrency(reportData.totalExpense, preferredCurrency), 18, 57);

        doc.setFillColor(255, 243, 243);
        doc.roundedRect(104, 42, 92, 20, 4, 4, "F");
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(...mutedColor);
        doc.text("TOTAL OUTSTANDING DEBT", 108, 49);
        doc.setFontSize(13);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(220, 50, 50);
        doc.text(formatCurrency(reportData.totalDebt, preferredCurrency), 108, 57);

        let yPos = 72;

        // --- Expenses Table ---
        if (includeExpenses && reportData.expenses.length > 0) {
            doc.setFont("helvetica", "bold");
            doc.setFontSize(11);
            doc.setTextColor(...darkColor);
            doc.text("Expenses", 14, yPos);
            yPos += 4;

            autoTable(doc, {
                startY: yPos,
                head: [["Date", "Subject", "Category", "Employee", "Amount"]],
                body: reportData.expenses.map(e => [
                    e.date || "",
                    e.subject || e.description || "â€”",
                    e.category || "â€”",
                    e.employee || "Me",
                    formatCurrency(e.amount, preferredCurrency),
                ]),
                headStyles: {
                    fillColor: accentColor,
                    textColor: [255, 255, 255],
                    fontStyle: "bold",
                    fontSize: 9,
                },
                bodyStyles: { fontSize: 9, textColor: [50, 50, 60] },
                alternateRowStyles: { fillColor: [245, 252, 253] },
                columnStyles: { 4: { halign: "right" } },
                margin: { left: 14, right: 14 },
            });
            yPos = (doc as any).lastAutoTable.finalY + 10;
        }

        // --- Debtors Table ---
        if (includeDebtors && reportData.debtors.length > 0) {
            if (yPos > 240) { doc.addPage(); yPos = 20; }
            doc.setFont("helvetica", "bold");
            doc.setFontSize(11);
            doc.setTextColor(...darkColor);
            doc.text("Debtors", 14, yPos);
            yPos += 4;

            autoTable(doc, {
                startY: yPos,
                head: [["Name", "Contact", "Total", "Paid", "Remaining", "Status"]],
                body: reportData.debtors.map(d => {
                    const remaining = d.amount - (d.paidAmount || 0);
                    return [
                        d.debtorName || "—",
                        d.email || d.phoneNumber || "—",
                        formatCurrency(d.amount, preferredCurrency),
                        formatCurrency(d.paidAmount || 0, preferredCurrency),
                        formatCurrency(remaining, preferredCurrency),
                        d.status === "paid" ? "Paid" : "Pending",
                    ];
                }),
                headStyles: {
                    fillColor: [220, 50, 50],
                    textColor: [255, 255, 255],
                    fontStyle: "bold",
                    fontSize: 9,
                },
                bodyStyles: { fontSize: 9, textColor: [50, 50, 60] },
                alternateRowStyles: { fillColor: [255, 248, 248] },
                columnStyles: {
                    2: { halign: "right" },
                    3: { halign: "right" },
                    4: { halign: "right" },
                    5: { halign: "center" },
                },
                margin: { left: 14, right: 14 },
            });
            yPos = (doc as any).lastAutoTable.finalY + 10;
        }

        // --- Payments Table ---
        if (reportData.payments.length > 0) {
            if (yPos > 240) { doc.addPage(); yPos = 20; }
            doc.setFont("helvetica", "bold");
            doc.setFontSize(11);
            doc.setTextColor(...darkColor);
            doc.text("Payments Received", 14, yPos);
            yPos += 4;

            autoTable(doc, {
                startY: yPos,
                head: [["Date", "Debtor", "Method", "Amount"]],
                body: reportData.payments.map(p => [
                    p.date || "",
                    p.debtorName || "—",
                    p.method || "Manual Entry",
                    formatCurrency(p.amount, preferredCurrency),
                ]),
                headStyles: {
                    fillColor: [34, 197, 94],
                    textColor: [255, 255, 255],
                    fontStyle: "bold",
                    fontSize: 9,
                },
                bodyStyles: { fontSize: 9, textColor: [50, 50, 60] },
                alternateRowStyles: { fillColor: [245, 255, 248] },
                columnStyles: { 3: { halign: "right" } },
                margin: { left: 14, right: 14 },
            });
            yPos = (doc as any).lastAutoTable.finalY + 10;
        }

        // --- Footer ---
        const pageHeight = doc.internal.pageSize.getHeight();
        doc.setFillColor(...darkColor);
        doc.rect(0, pageHeight - 14, pageWidth, 14, "F");
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(150, 150, 160);
        doc.text("Generated by Spendora  â€¢  spendora.app", 14, pageHeight - 5);
        doc.text(`Generated on ${new Date().toLocaleDateString()}`, pageWidth - 14, pageHeight - 5, { align: "right" });

        doc.save(`spendora-report-${startDate}-to-${endDate}.pdf`);
    };

    const cardStyle = {
        background: "var(--bg-surface)",
        border: "1px solid var(--border)",
    };

    const inputStyle = {
        background: "var(--bg-base)",
        border: "1px solid var(--border)",
        color: "var(--text-primary)",
    };

    return (
        <div className="max-w-4xl mx-auto py-10 px-6 animate-in fade-in slide-in-from-bottom-4 duration-700">
            <div className="flex items-center space-x-4 mb-8">
                <div className="p-3 rounded-2xl bg-cyan-500/10 text-cyan-500">
                    <FileText size={32} />
                </div>
                <div>
                    <h1 className="text-3xl font-extrabold" style={{ color: "var(--text-primary)" }}>
                        Financial Reports
                    </h1>
                    <p className="text-sm" style={{ color: "var(--text-muted)" }}>
                        Generate and export your financial summaries
                    </p>
                </div>
            </div>

            {step === 1 ? (
                <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                    <div className="md:col-span-2 space-y-8">
                        <div className="rounded-[2.5rem] p-8 shadow-xl" style={cardStyle}>
                            <h2 className="text-xl font-bold mb-6 flex items-center gap-2" style={{ color: "var(--text-primary)" }}>
                                <CalendarIcon size={20} className="text-[var(--accent)]" />
                                Select Time Period
                            </h2>
                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                                <div className="space-y-2">
                                    <label className="text-xs font-bold uppercase tracking-wider opacity-60" style={{ color: "var(--text-secondary)" }}>
                                        Start Date
                                    </label>
                                    <input
                                        type="date"
                                        className="w-full px-4 py-3 rounded-xl outline-none"
                                        style={inputStyle}
                                        value={startDate}
                                        onChange={(e) => setStartDate(e.target.value)}
                                    />
                                </div>
                                <div className="space-y-2">
                                    <label className="text-xs font-bold uppercase tracking-wider opacity-60" style={{ color: "var(--text-secondary)" }}>
                                        End Date
                                    </label>
                                    <input
                                        type="date"
                                        className="w-full px-4 py-3 rounded-xl outline-none"
                                        style={inputStyle}
                                        value={endDate}
                                        onChange={(e) => setEndDate(e.target.value)}
                                    />
                                </div>
                            </div>
                        </div>

                        <div className="rounded-[2.5rem] p-8 shadow-xl" style={cardStyle}>
                            <h2 className="text-xl font-bold mb-6 flex items-center gap-2" style={{ color: "var(--text-primary)" }}>
                                <Filter size={20} className="text-[var(--accent)]" />
                                Report Details
                            </h2>
                            <div className="space-y-4">
                                {[
                                    { label: "Include Expenses", state: includeExpenses, setter: setIncludeExpenses },
                                    { label: "Include Debtors Info", state: includeDebtors, setter: setIncludeDebtors },
                                    { label: "Fully Paid Debtors of the Month", state: includePaidDebtors, setter: setIncludePaidDebtors },
                                ].map((item) => (
                                    <label
                                        key={item.label}
                                        className="flex items-center justify-between p-4 rounded-2xl cursor-pointer transition-all hover:bg-[var(--bg-elevated)]"
                                        style={{ border: "1px solid var(--border)" }}
                                    >
                                        <span className="font-medium" style={{ color: "var(--text-primary)" }}>{item.label}</span>
                                        <input
                                            type="checkbox"
                                            className="w-5 h-5 accent-[var(--accent)]"
                                            checked={item.state}
                                            onChange={(e) => item.setter(e.target.checked)}
                                        />
                                    </label>
                                ))}
                            </div>
                        </div>
                    </div>

                    <div className="space-y-6">
                        <div className="rounded-[2.5rem] p-8 text-center space-y-4 shadow-xl" style={cardStyle}>
                            <div className="p-4 rounded-full bg-cyan-500/10 text-cyan-500 w-fit mx-auto mb-2">
                                <ArrowRight size={32} />
                            </div>
                            <h3 className="text-lg font-bold" style={{ color: "var(--text-primary)" }}>Ready to Generate?</h3>
                            <p className="text-sm" style={{ color: "var(--text-muted)" }}>
                                We'll prepare a summary of your filtered data for you to review.
                            </p>
                            <button
                                onClick={() => setStep(2)}
                                className="w-full py-4 rounded-xl font-bold text-black transition-all hover:scale-105 active:scale-95"
                                style={{ background: "var(--accent)" }}
                            >
                                Generate Preview
                            </button>
                        </div>
                    </div>
                </div>
            ) : (
                <div className="animate-in fade-in slide-in-from-right-4 duration-500 space-y-8">
                    <div className="rounded-[2.5rem] p-8 shadow-xl" style={cardStyle}>
                        <div className="flex justify-between items-center mb-8 pb-4 border-b border-[var(--border)]">
                            <h2 className="text-2xl font-bold" style={{ color: "var(--text-primary)" }}>Report Preview</h2>
                            <button
                                onClick={() => setStep(1)}
                                className="text-xs font-bold uppercase tracking-widest hover:text-[var(--accent)]"
                                style={{ color: "var(--text-muted)" }}
                            >
                                Back to Settings
                            </button>
                        </div>

                        <div className="space-y-8">
                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                <div className="p-6 rounded-2xl bg-[var(--bg-elevated)] border border-[var(--border)]">
                                    <p className="text-xs font-bold uppercase opacity-50 mb-1" style={{ color: "var(--text-muted)" }}>Total Expenses</p>
                                    <p className="text-2xl font-bold text-[var(--accent)]">
                                        {formatCurrency(reportData.totalExpense, preferredCurrency)}
                                    </p>
                                </div>
                                <div className="p-6 rounded-2xl bg-[var(--bg-elevated)] border border-[var(--border)]">
                                    <p className="text-xs font-bold uppercase opacity-50 mb-1" style={{ color: "var(--text-muted)" }}>Total Outstanding Debt</p>
                                    <p className="text-2xl font-bold text-red-500">
                                        {formatCurrency(reportData.totalDebt, preferredCurrency)}
                                    </p>
                                </div>
                            </div>

                            <div className="p-6 rounded-2xl bg-[var(--bg-base)] border border-[var(--border)] max-h-96 overflow-y-auto">
                                <pre className="text-sm whitespace-pre-wrap font-sans leading-relaxed" style={{ color: "var(--text-secondary)" }}>
                                    {generateReportText()}
                                </pre>
                            </div>

                            <div className="flex flex-col sm:flex-row gap-4">
                                <button
                                    onClick={handleSendEmail}
                                    className="flex-1 py-4 rounded-xl font-bold text-black flex items-center justify-center gap-3 transition-all hover:scale-105"
                                    style={{ background: "var(--accent)" }}
                                >
                                    <Mail size={20} />
                                    Email Report
                                </button>
                                <button
                                    onClick={handleDownloadPDF}
                                    className="flex-1 py-4 rounded-xl font-bold transition-all border border-[var(--border)] bg-[var(--bg-elevated)] flex items-center justify-center gap-3 hover:bg-[var(--bg-muted)]"
                                    style={{ color: "var(--text-primary)" }}
                                >
                                    <Download size={20} />
                                    Download PDF
                                </button>
                            </div>
                        </div>
                    </div>

                    <div className="flex items-center justify-center gap-3 p-6 rounded-3xl bg-green-500/10 border border-green-500/20 text-green-500">
                        <CheckCircle2 size={24} />
                        <span className="font-medium">You can now send this report directly to your email.</span>
                    </div>
                </div>
            )}
        </div>
    );
}

